export const SET_TOKEN='SET_TOKEN';
export const AUTH_LOGOUT='AUTH_LOGOUT';

export const GET_USER_DETAILS_SUCCESS='GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_START='GET_USER_DETAILS_START';

export const GET_PROFILE_SUCCESS='GET_PROFILE_SUCCESS';
export const GET_PROFILE_START='GET_PROFILE_START';
export const GET_PROFILE_FAILURE='GET_PROFILE_FAILURE';



export const GET_POST_START='GET_POST_START';
export const GET_POST_SUCCESS='GET_POST_SUCCESS';
export const GET_POST_FAILURE='GET_POST_FAILURE';



export const CREATE_POST_START='CREATE_POST_START';
export const CREATE_POST_SUCCESS='CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE='CREATE_POST_FAILURE';



export const GET_COMMENT_START='GET_COMMENT_START';
export const GET_COMMENT_SUCCESS='GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAILURE='GET_COMMENT_FAILURE';



export const CREATE_COMMENT_START='CREATE_COMMENT_START';
export const CREATE_COMMENT_SUCCESS='CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE='CREATE_COMMENT_FAILURE';

export const SET_FETCH_MORE_POST='SET_FETCH_MORE_POST';
export const PAGE_ZERO_ACTION='PAGE_ZERO_ACTION';



export const LIKE_POST="LIKE_POST";
export const UNLIKE_POST="UNLIKE_POST";

export const DISLIKE_POST="DISLIKE_POST";
export const UNDISLIKE_POST="UNDISLIKE_POST";