export const SET_TOKEN='SET_TOKEN';
export const AUTH_LOGOUT='AUTH_LOGOUT';

export const GET_USER_DETAILS_SUCCESS='GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_START='GET_USER_DETAILS_START';

export const GET_PROFILE_SUCCESS='GET_PROFILE_SUCCESS';
export const GET_PROFILE_START='GET_PROFILE_START';
export const GET_PROFILE_FAILURE='GET_PROFILE_FAILURE';
